<?php

declare(strict_types=1);

namespace FPTracking\Admin;

use FPTracking\Catalog\EventCatalog;

/**
 * Generates a GTM container JSON export ready to import in Google Tag Manager.
 *
 * The export includes:
 *  - Variables: dataLayer variables for all event params + GA4/Ads/Meta IDs
 *  - Triggers:  one Custom Event trigger per tracked event
 *  - Tags:      GA4 Configuration, GA4 Event tags, Google Ads Conversion,
 *               Meta Pixel base + event tags, Consent Mode initialization
 */
final class GTMExporter {

    /** All events fired by the FP tracking stack */
    public const EVENTS = EventCatalog::EVENTS;

    /** Meta event mapping: FP event → Meta standard event */
    private const META_EVENT_MAP = EventCatalog::META_EVENT_MAP;

    /** Google Ads conversion events — driven by Settings::ADS_EVENTS */

    public function __construct(private readonly Settings $settings) {}

    /**
     * Generates the full GTM container JSON as a PHP array, then encodes it.
     */
    public function generate(): string {
        $ga4_id    = $this->settings->get('ga4_measurement_id', 'G-XXXXXXXXXX');
        $ads_id    = $this->settings->get('google_ads_id', 'AW-XXXXXXXXX');
        $meta_id   = $this->settings->get('meta_pixel_id', '');
        $site_url  = get_bloginfo('url');
        $site_name = get_bloginfo('name');

        $variables = $this->build_variables($ga4_id, $ads_id, $meta_id);
        $triggers  = $this->build_triggers();
        $tags      = $this->build_tags($ga4_id, $ads_id, $meta_id, $triggers, $variables);

        $container = [
            'exportFormatVersion' => 2,
            'exportTime'          => gmdate('Y-m-d H:i:s'),
            'containerVersion'    => [
                'path'              => 'accounts/0/containers/0/versions/0',
                'accountId'         => '0',
                'containerId'       => '0',
                'containerVersionId'=> '0',
                'name'              => 'FP Tracking — ' . $site_name,
                'description'       => 'Auto-generated by FP-Marketing-Tracking-Layer. Site: ' . $site_url,
                'container'         => [
                    'path'          => 'accounts/0/containers/0',
                    'accountId'     => '0',
                    'containerId'   => '0',
                    'name'          => 'FP Tracking — ' . $site_name,
                    'publicId'      => $this->settings->get('gtm_id', 'GTM-XXXXXXX'),
                    'usageContext'  => ['WEB'],
                ],
                'variable'          => array_values($variables),
                'trigger'           => array_values($triggers),
                'tag'               => array_values($tags),
            ],
        ];

        return (string) wp_json_encode($container, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    }

    // -------------------------------------------------------------------------
    // VARIABLES
    // -------------------------------------------------------------------------

    private function build_variables(string $ga4_id, string $ads_id, string $meta_id): array {
        $vars = [];
        $id   = 1;

        // Constant variables for IDs
        $vars['ga4_id'] = $this->make_constant_var($id++, 'FP - GA4 Measurement ID', $ga4_id);
        $vars['ads_id'] = $this->make_constant_var($id++, 'FP - Google Ads ID', $ads_id);
        $vars['meta_id'] = $this->make_constant_var($id++, 'FP - Meta Pixel ID', $meta_id ?: 'PIXEL_ID');

        // dataLayer variables for common event params
        $dl_params = [
            // Core
            'event_id'          => 'FP - DL event_id',
            'transaction_id'    => 'FP - DL transaction_id',
            'value'             => 'FP - DL value',
            'currency'          => 'FP - DL currency',
            'items'             => 'FP - DL items',
            // Forms
            'form_id'           => 'FP - DL form_id',
            'form_title'        => 'FP - DL form_title',
            'form_type'         => 'FP - DL form_type',
            'submission_id'     => 'FP - DL submission_id',
            'step'              => 'FP - DL step',
            'fields_filled'     => 'FP - DL fields_filled',
            // Click events — actual param names from fp-tracking.js
            'link_type'         => 'FP - DL link_type',
            'link_url'          => 'FP - DL link_url',
            'link_text'         => 'FP - DL link_text',
            'link_domain'       => 'FP - DL link_domain',
            'phone_number'      => 'FP - DL phone_number',
            'email_address'     => 'FP - DL email_address',
            'whatsapp_number'   => 'FP - DL whatsapp_number',
            'social_network'    => 'FP - DL social_network',
            'map_address'       => 'FP - DL map_address',
            // Scroll
            'percent_scrolled'  => 'FP - DL percent_scrolled',
            // Video
            'video_title'       => 'FP - DL video_title',
            'video_url'         => 'FP - DL video_url',
            'video_provider'    => 'FP - DL video_provider',
            'video_duration'    => 'FP - DL video_duration',
            // Search
            'search_term'       => 'FP - DL search_term',
            // File download
            'file_url'          => 'FP - DL file_url',
            'file_name'         => 'FP - DL file_name',
            'file_extension'    => 'FP - DL file_extension',
            // Booking (Restaurant)
            'reservation_id'       => 'FP - DL reservation_id',
            'reservation_location' => 'FP - DL reservation_location',
            'reservation_party'    => 'FP - DL reservation_party',
            'reservation_date'     => 'FP - DL reservation_date',
            'meal_type'            => 'FP - DL meal_type',
            // Experiences
            'experience_id'        => 'FP - DL experience_id',
            'experience_title'     => 'FP - DL experience_title',
            // FP-CTA-Bar
            'cta_label'         => 'FP - DL cta_label',
            'cta_action'        => 'FP - DL cta_action',
            'cta_url'           => 'FP - DL cta_url',
            // FP-Bio-Standalone
            'bio_link_label'    => 'FP - DL bio_link_label',
            'bio_link_url'      => 'FP - DL bio_link_url',
            'bio_link_category' => 'FP - DL bio_link_category',
            // FP-Discount-Gift
            'coupon'            => 'FP - DL coupon',
            'reason'            => 'FP - DL reason',
            'voucher_id'        => 'FP - DL voucher_id',
            'order_id'          => 'FP - DL order_id',
            'source'            => 'FP - DL source',
            // Error events
            'error_message'     => 'FP - DL error_message',
            'error_type'        => 'FP - DL error_type',
        ];

        foreach ($dl_params as $param => $label) {
            $vars[$param] = $this->make_datalayer_var($id++, $label, $param);
        }

        return $vars;
    }

    private function make_constant_var(int $id, string $name, string $value): array {
        return [
            'accountId'   => '0',
            'containerId' => '0',
            'variableId'  => (string) $id,
            'name'        => $name,
            'type'        => 'c',
            'parameter'   => [
                ['type' => 'template', 'key' => 'value', 'value' => $value],
            ],
        ];
    }

    private function make_datalayer_var(int $id, string $name, string $param): array {
        return [
            'accountId'   => '0',
            'containerId' => '0',
            'variableId'  => (string) $id,
            'name'        => $name,
            'type'        => 'v',
            'parameter'   => [
                ['type' => 'integer', 'key' => 'dataLayerVersion', 'value' => '2'],
                ['type' => 'boolean', 'key' => 'setDefaultValue',  'value' => 'false'],
                ['type' => 'template', 'key' => 'name',            'value' => $param],
            ],
        ];
    }

    // -------------------------------------------------------------------------
    // TRIGGERS
    // -------------------------------------------------------------------------

    private function build_triggers(): array {
        $triggers = [];
        $id       = 100;

        // All Pages trigger
        $triggers['all_pages'] = [
            'accountId'   => '0',
            'containerId' => '0',
            'triggerId'   => (string) $id++,
            'name'        => 'FP - All Pages',
            'type'        => 'PAGEVIEW',
        ];

        // One Custom Event trigger per FP event
        foreach (self::EVENTS as $event_name => $meta) {
            $triggers[$event_name] = [
                'accountId'   => '0',
                'containerId' => '0',
                'triggerId'   => (string) $id++,
                'name'        => 'FP - Event: ' . $meta['label'],
                'type'        => 'CUSTOM_EVENT',
                'customEventFilter' => [
                    [
                        'type'      => 'EQUALS',
                        'parameter' => [
                            ['type' => 'template', 'key' => 'arg0', 'value' => '{{_event}}'],
                            ['type' => 'template', 'key' => 'arg1', 'value' => $event_name],
                        ],
                    ],
                ],
            ];
        }

        // Consent initialization trigger (DOM Ready)
        $triggers['consent_init'] = [
            'accountId'   => '0',
            'containerId' => '0',
            'triggerId'   => (string) $id++,
            'name'        => 'FP - Consent Initialization',
            'type'        => 'DOM_READY',
        ];

        return $triggers;
    }

    // -------------------------------------------------------------------------
    // TAGS
    // -------------------------------------------------------------------------

    private function build_tags(string $ga4_id, string $ads_id, string $meta_id, array $triggers, array $variables): array {
        $tags = [];
        $id   = 200;

        // --- Consent Mode initialization tag (fires before everything) ---
        $tags['consent_init'] = [
            'accountId'   => '0',
            'containerId' => '0',
            'tagId'       => (string) $id++,
            'name'        => 'FP - Consent Mode v2 Init',
            'type'        => 'html',
            'priority'    => ['type' => 'integer', 'key' => 'priority', 'value' => '10'],
            'parameter'   => [
                [
                    'type'  => 'template',
                    'key'   => 'html',
                    'value' => "<script>\nwindow.dataLayer = window.dataLayer || [];\nfunction gtag(){dataLayer.push(arguments);}\ngtag('consent','default',{\n  'analytics_storage':'denied',\n  'ad_storage':'denied',\n  'ad_user_data':'denied',\n  'ad_personalization':'denied',\n  'functionality_storage':'granted',\n  'security_storage':'granted',\n  'wait_for_update': 500\n});\n</script>",
                ],
                ['type' => 'boolean', 'key' => 'supportDocumentWrite', 'value' => 'false'],
            ],
            'firingTriggerId' => [$triggers['consent_init']['triggerId']],
        ];

        // --- GA4 Configuration tag ---
        $tags['ga4_config'] = [
            'accountId'   => '0',
            'containerId' => '0',
            'tagId'       => (string) $id++,
            'name'        => 'FP - GA4 Configuration',
            'type'        => 'googtag',
            'parameter'   => [
                ['type' => 'template', 'key' => 'tagId', 'value' => '{{' . $variables['ga4_id']['name'] . '}}'],
            ],
            'firingTriggerId' => [$triggers['all_pages']['triggerId']],
        ];

        // --- GA4 Event tags ---
        foreach (self::EVENTS as $event_name => $meta) {
            if ($event_name === 'page_view') {
                continue; // handled by GA4 config tag automatically
            }

            $parameters = $this->build_ga4_event_parameters($event_name, $variables);

            $tags['ga4_event_' . $event_name] = [
                'accountId'   => '0',
                'containerId' => '0',
                'tagId'       => (string) $id++,
                'name'        => 'FP - GA4 Event: ' . $meta['label'],
                'type'        => 'gaawe',
                'parameter'   => array_merge(
                    [
                        ['type' => 'template', 'key' => 'measurementId', 'value' => '{{' . $variables['ga4_id']['name'] . '}}'],
                        ['type' => 'template', 'key' => 'eventName',     'value' => $event_name],
                    ],
                    $parameters ? [['type' => 'list', 'key' => 'eventParameters', 'list' => $parameters]] : []
                ),
                'firingTriggerId' => [$triggers[$event_name]['triggerId']],
            ];
        }

        // --- Google Ads Conversion tags ---
        if ($ads_id) {
            foreach (Settings::ADS_EVENTS as $event_name => $event_human_label) {
                if (!isset($triggers[$event_name])) {
                    continue;
                }

                // Read conversion label saved in admin (may be empty — tag still created as placeholder)
                $conversion_label = $this->settings->get_ads_label($event_name);

                // Use event label from EVENTS map if available, else fall back to ADS_EVENTS label
                $tag_label = self::EVENTS[$event_name]['label'] ?? $event_human_label;

                $tags['ads_' . $event_name] = [
                    'accountId'   => '0',
                    'containerId' => '0',
                    'tagId'       => (string) $id++,
                    'name'        => 'FP - Google Ads: ' . $tag_label . ($conversion_label ? '' : ' ⚠ label missing'),
                    'type'        => 'awct',
                    'parameter'   => [
                        ['type' => 'template', 'key' => 'conversionId',    'value' => '{{' . $variables['ads_id']['name'] . '}}'],
                        ['type' => 'template', 'key' => 'conversionLabel', 'value' => $conversion_label],
                        ['type' => 'template', 'key' => 'conversionValue', 'value' => '{{' . $variables['value']['name'] . '}}'],
                        ['type' => 'template', 'key' => 'currencyCode',    'value' => '{{' . $variables['currency']['name'] . '}}'],
                        ['type' => 'template', 'key' => 'orderId',         'value' => '{{' . $variables['transaction_id']['name'] . '}}'],
                        ['type' => 'boolean',  'key' => 'enableNewCustomerReporting', 'value' => 'false'],
                    ],
                    'firingTriggerId' => [$triggers[$event_name]['triggerId']],
                ];
            }
        }

        // --- Meta Pixel Base Code tag ---
        if ($meta_id) {
            $tags['meta_base'] = [
                'accountId'   => '0',
                'containerId' => '0',
                'tagId'       => (string) $id++,
                'name'        => 'FP - Meta Pixel Base Code',
                'type'        => 'html',
                'parameter'   => [
                    [
                        'type'  => 'template',
                        'key'   => 'html',
                        'value' => $this->meta_base_html(),
                    ],
                    ['type' => 'boolean', 'key' => 'supportDocumentWrite', 'value' => 'false'],
                ],
                'firingTriggerId' => [$triggers['all_pages']['triggerId']],
            ];

            // Meta event tags
            foreach (self::META_EVENT_MAP as $fp_event => $meta_event) {
                if (!isset($triggers[$fp_event])) {
                    continue;
                }
                $events_with_value = [
                    'purchase', 'event_ticket_purchase',
                    'booking_confirmed', 'booking_payment_completed',
                    'experience_paid', 'rtb_approved', 'gift_purchased',
                    'add_to_cart', 'begin_checkout', 'form_payment_started',
                ];
                $value_param = in_array($fp_event, $events_with_value, true)
                    ? "fbq('track', '" . $meta_event . "', {value: {{" . $variables['value']['name'] . "}}, currency: {{" . $variables['currency']['name'] . "}} || 'EUR', eventID: {{" . $variables['event_id']['name'] . "}}});"
                    : "fbq('track', '" . $meta_event . "', {eventID: {{" . $variables['event_id']['name'] . "}}});";

                $tags['meta_event_' . $fp_event] = [
                    'accountId'   => '0',
                    'containerId' => '0',
                    'tagId'       => (string) $id++,
                    'name'        => 'FP - Meta: ' . self::EVENTS[$fp_event]['label'],
                    'type'        => 'html',
                    'parameter'   => [
                        [
                            'type'  => 'template',
                            'key'   => 'html',
                            'value' => '<script>' . $value_param . '</script>',
                        ],
                        ['type' => 'boolean', 'key' => 'supportDocumentWrite', 'value' => 'false'],
                    ],
                    'firingTriggerId' => [$triggers[$fp_event]['triggerId']],
                ];
            }
        }

        return $tags;
    }

    /**
     * Builds the GA4 event parameters list for a given event.
     */
    private function build_ga4_event_parameters(string $event_name, array $variables): array {
        // Common params for all events
        $common = [
            'event_id' => $variables['event_id']['name'],
        ];

        // Event-specific params — param names MUST match exactly what fp-tracking.js / PHP bridges push
        $specific = match (true) {

            // ── WooCommerce ecommerce ────────────────────────────────────────
            in_array($event_name, ['purchase', 'event_ticket_purchase'], true) => [
                'transaction_id' => $variables['transaction_id']['name'],
                'value'          => $variables['value']['name'],
                'currency'       => $variables['currency']['name'],
                'items'          => $variables['items']['name'],
            ],
            in_array($event_name, ['add_to_cart', 'view_item', 'begin_checkout'], true) => [
                'value'    => $variables['value']['name'],
                'currency' => $variables['currency']['name'],
                'items'    => $variables['items']['name'],
            ],

            // ── Lead / Forms ─────────────────────────────────────────────────
            $event_name === 'generate_lead' => [
                'form_id'    => $variables['form_id']['name'],
                'form_title' => $variables['form_title']['name'],
                'form_type'  => $variables['form_type']['name'],
            ],
            $event_name === 'form_payment_started' => [
                'form_id'  => $variables['form_id']['name'],
                'value'    => $variables['value']['name'],
                'currency' => $variables['currency']['name'],
            ],
            in_array($event_name, ['contact_form_submit'], true) => [
                'form_id'   => $variables['form_id']['name'],
                'form_type' => $variables['form_type']['name'],
            ],
            in_array($event_name, ['form_view', 'form_start', 'form_abandon', 'form_submit_attempt', 'fp_form_submit_success'], true) => [
                'form_id'    => $variables['form_id']['name'],
                'form_title' => $variables['form_title']['name'],
            ],
            $event_name === 'form_step_complete' => [
                'form_id' => $variables['form_id']['name'],
                'step'    => $variables['step']['name'],
            ],
            $event_name === 'form_submit_error' => [
                'form_id'       => $variables['form_id']['name'],
                'error_message' => $variables['error_message']['name'],
                'error_type'    => $variables['error_type']['name'],
            ],

            // ── Restaurant Reservations ──────────────────────────────────────
            in_array($event_name, ['booking_confirmed', 'booking_submitted', 'booking_payment_required', 'waitlist_joined'], true) => [
                'transaction_id'       => $variables['transaction_id']['name'],
                'value'                => $variables['value']['name'],
                'currency'             => $variables['currency']['name'],
                'reservation_id'       => $variables['reservation_id']['name'],
                'reservation_location' => $variables['reservation_location']['name'],
                'reservation_party'    => $variables['reservation_party']['name'],
                'reservation_date'     => $variables['reservation_date']['name'],
                'meal_type'            => $variables['meal_type']['name'],
            ],
            $event_name === 'booking_payment_completed' => [
                'transaction_id'       => $variables['transaction_id']['name'],
                'value'                => $variables['value']['name'],
                'currency'             => $variables['currency']['name'],
                'reservation_id'       => $variables['reservation_id']['name'],
                'reservation_location' => $variables['reservation_location']['name'],
                'reservation_party'    => $variables['reservation_party']['name'],
                'reservation_date'     => $variables['reservation_date']['name'],
                'meal_type'            => $variables['meal_type']['name'],
            ],
            in_array($event_name, ['booking_cancelled', 'booking_no_show', 'booking_visited', 'waitlist_promoted', 'booking_moved'], true) => [
                'reservation_id'       => $variables['reservation_id']['name'],
                'reservation_location' => $variables['reservation_location']['name'],
                'reservation_party'    => $variables['reservation_party']['name'],
                'reservation_date'     => $variables['reservation_date']['name'],
                'meal_type'            => $variables['meal_type']['name'],
            ],
            in_array($event_name, ['booking_form_view', 'booking_form_start', 'booking_form_abandon', 'booking_step_complete', 'booking_submit_error'], true) => [
                'reservation_id'       => $variables['reservation_id']['name'],
                'reservation_location' => $variables['reservation_location']['name'],
            ],

            // ── FP-Experiences (eventi con revenue) ──────────────────────────
            in_array($event_name, [
                'experience_paid', 'rtb_approved', 'gift_purchased', 'rtb_submitted',
            ], true) => [
                'transaction_id'   => $variables['transaction_id']['name'],
                'experience_id'    => $variables['experience_id']['name'],
                'experience_title' => $variables['experience_title']['name'],
                'value'            => $variables['value']['name'],
                'currency'         => $variables['currency']['name'],
                'reservation_id'   => $variables['reservation_id']['name'],
            ],

            // ── FP-Experiences (eventi senza revenue) ────────────────────────
            in_array($event_name, [
                'experience_view', 'experience_checkout_view', 'gift_redeem_view',
                'booking_start', 'booking_abandon', 'rtb_start', 'gift_start',
                'experience_checkout_started', 'experience_cancelled',
                'rtb_declined', 'rtb_hold_expired', 'gift_redeemed',
            ], true) => [
                'experience_id'    => $variables['experience_id']['name'],
                'experience_title' => $variables['experience_title']['name'],
            ],

            // ── Click events — param names match fp-tracking.js output ───────
            $event_name === 'click_phone' => [
                'link_type'    => $variables['link_type']['name'],
                'phone_number' => $variables['phone_number']['name'],
                'link_text'    => $variables['link_text']['name'],
                'link_url'     => $variables['link_url']['name'],
            ],
            $event_name === 'click_whatsapp' => [
                'link_type'       => $variables['link_type']['name'],
                'whatsapp_number' => $variables['whatsapp_number']['name'],
                'link_text'       => $variables['link_text']['name'],
                'link_url'        => $variables['link_url']['name'],
            ],
            $event_name === 'click_email' => [
                'link_type'     => $variables['link_type']['name'],
                'email_address' => $variables['email_address']['name'],
                'link_text'     => $variables['link_text']['name'],
                'link_url'      => $variables['link_url']['name'],
            ],
            $event_name === 'click_map' => [
                'link_type'   => $variables['link_type']['name'],
                'map_address' => $variables['map_address']['name'],
                'link_url'    => $variables['link_url']['name'],
            ],
            in_array($event_name, ['click_social'], true) => [
                'link_type'      => $variables['link_type']['name'],
                'social_network' => $variables['social_network']['name'],
                'link_text'      => $variables['link_text']['name'],
                'link_url'       => $variables['link_url']['name'],
            ],
            in_array($event_name, ['click_external_link', 'click_cta'], true) => [
                'link_type'   => $variables['link_type']['name'],
                'link_url'    => $variables['link_url']['name'],
                'link_domain' => $variables['link_domain']['name'],
                'link_text'   => $variables['link_text']['name'],
            ],

            // ── Engagement ───────────────────────────────────────────────────
            $event_name === 'scroll_depth' => [
                'percent_scrolled' => $variables['percent_scrolled']['name'],
            ],
            $event_name === 'video_complete' => [
                'video_title'    => $variables['video_title']['name'],
                'video_url'      => $variables['video_url']['name'],
                'video_provider' => $variables['video_provider']['name'],
                'video_duration' => $variables['video_duration']['name'],
            ],
            $event_name === 'search' => [
                'search_term' => $variables['search_term']['name'],
            ],
            $event_name === 'file_download' => [
                'file_name'      => $variables['file_name']['name'],
                'file_extension' => $variables['file_extension']['name'],
                'file_url'       => $variables['file_url']['name'],
                'link_text'      => $variables['link_text']['name'],
            ],

            // ── FP-CTA-Bar ───────────────────────────────────────────────────
            $event_name === 'cta_bar_click' => [
                'cta_label'  => $variables['cta_label']['name'],
                'cta_action' => $variables['cta_action']['name'],
                'cta_url'    => $variables['cta_url']['name'],
            ],

            // ── FP-Bio-Standalone ────────────────────────────────────────────
            $event_name === 'bio_link_click' => [
                'bio_link_label'    => $variables['bio_link_label']['name'],
                'bio_link_url'      => $variables['bio_link_url']['name'],
                'bio_link_category' => $variables['bio_link_category']['name'],
            ],

            // ── FP-Discount-Gift ────────────────────────────────────────────
            $event_name === 'discount_applied' => [
                'coupon'   => $variables['coupon']['name'],
                'value'    => $variables['value']['name'],
                'currency' => $variables['currency']['name'],
                'source'   => $variables['source']['name'],
            ],
            $event_name === 'discount_code_attempted' => [
                'coupon'   => $variables['coupon']['name'],
                'currency' => $variables['currency']['name'],
                'source'   => $variables['source']['name'],
            ],
            $event_name === 'discount_code_rejected' => [
                'coupon'   => $variables['coupon']['name'],
                'reason'   => $variables['reason']['name'],
                'currency' => $variables['currency']['name'],
                'source'   => $variables['source']['name'],
            ],
            $event_name === 'discount_removed' => [
                'coupon'   => $variables['coupon']['name'],
                'currency' => $variables['currency']['name'],
                'source'   => $variables['source']['name'],
            ],
            $event_name === 'gift_voucher_purchased' => [
                'voucher_id' => $variables['voucher_id']['name'],
                'order_id'   => $variables['order_id']['name'],
                'source'     => $variables['source']['name'],
            ],
            $event_name === 'gift_voucher_redeemed' => [
                'voucher_id'     => $variables['voucher_id']['name'],
                'order_id'       => $variables['order_id']['name'],
                'reservation_id' => $variables['reservation_id']['name'],
                'source'         => $variables['source']['name'],
            ],

            default => [],
        };

        $all_params = array_merge($common, $specific);

        return array_map(
            static fn(string $key, string $var_name): array => [
                'type' => 'map',
                'map'  => [
                    ['type' => 'template', 'key' => 'name',  'value' => $key],
                    ['type' => 'template', 'key' => 'value', 'value' => '{{' . $var_name . '}}'],
                ],
            ],
            array_keys($all_params),
            array_values($all_params)
        );
    }

    /**
     * Returns the Meta Pixel base code HTML (uses {{FP - Meta Pixel ID}} variable).
     */
    private function meta_base_html(): string {
        return <<<'HTML'
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '{{FP - Meta Pixel ID}}');
fbq('track', 'PageView');
</script>
HTML;
    }
}
